### ISSUE TITLE
Nhentai: JSError [PaperbackError(300)] JSError Error: JSON PARSE ERROR!

### ISSUE THREAD

**Issue by StateFarmTaxes** [TheNetsky/community-extensions#5]
Happens from time to time when I try to open new uploads category on Nhentai. I've already set my settings to default but still the same error. Probably due to a specific doujin causing a error?
![riguma](https://github.com/TheNetsky/community-extensions/assets/123421684/ff5f25ae-3dea-43d5-8227-2440b7d358ff)

**Comment by TheNetsky** [comment]
Known.

**Comment by henderea** [comment]
This is actually an issue with the site's API. Some series can mess up the response it gives sometimes, causing the error. No idea what the criteria is for what messes it up. Not an app issue, really, because if you load the API request in your browser, it has the same issue. But the actual site works fine. It's just the API.

**Comment by TheNetsky** [comment]
So it'll likely fix itself then.

**Comment by henderea** [comment]
Actually, no, not from my experience. Some of the bugged searches have continued to have the issue at whatever series is bad for months now. I think sometimes an individual series details/chapter page will fix over time, but I don't think the bugged searches ever fix. Eventually, the series goes far enough down in the search that it isn't a major issue, but you'll still hit a wall if you scroll far enough.

**Comment by TheNetsky** [comment]
Solution being... just remove the section?

**Comment by henderea** [comment]
More like wait for it to pass. If it's only the newest X, then it will pass soon enough. And maybe come back later, but that would pass too.

**Comment by henderea** [comment]
Specifically, the cause is some individual item in the search that bugs the API request out. If you're sorting by most recent, that item will eventually stop being on the first page of results. And then it will move to the second page, the third page, and so on until you hardly notice it unless you scroll way back. It tends to be a temporary issue for most users since it moves into later pages over time and you'll stop hitting the issue unless you scroll down far enough. But the series causing the issue never seems to get fixed, so you'll still hit it if the page of results includes that entry.
